# =============================================================================
# 01c_build_td_rates_20260806.R — Implied rates on insured vs uninsured time
# deposits from Call Report RI items 2.a.2.b / 2.a.2.c.
#
# RIADHK03 (int_exp_time_ins):   interest on time deposits <= $250,000 (YTD)
# RIADHK04 (int_exp_time_unins): interest on time deposits >  $250,000 (YTD)
# Balances: ins_time_deps / unins_time_deps (RC-E, same $250k threshold).
#
# Output: tracks/fdic-brc-jfqa-aug2026/data/td_rates_YYYYMMDD.rds
#   ID_RSSD, D_DT, rate_ins_td, rate_unins_td, rate_spread_td (annualized %)
# Consumed by: code/result-generation/td_rate_spread_20260806.qmd
# Raw inputs generated by the shared call-report pull (data/raw/*_20260401_*.rds).
# =============================================================================
rm(list = ls())

library(data.table)
library(here)
library(lubridate)

source(here::here("code", "_common.R"))
source(here::here("tracks", "fdic-brc-jfqa-aug2026", "code", "_track_common.R"))

dat_suffix <- format(Sys.time(), "%Y%m%d")

dt1 <- readRDS(here::here("data", "raw", "call_report_data_20260401_1.rds"))
dt2 <- readRDS(here::here("data", "raw", "call_report_data_20260401_2.rds"))
setDT(dt1); setDT(dt2)
dt <- rbind(dt1, dt2, fill = TRUE)
rm(dt1, dt2); gc()

dt[, D_DT := as.Date(D_DT)]
dt[, cal_year := as.integer(format(D_DT, "%Y"))]
dt[, quarter_no := lubridate::quarter(D_DT)]
dt <- unique(dt, by = c("ID_RSSD", "D_DT"))
setorder(dt, ID_RSSD, D_DT)

# --- de-cumulate YTD interest expense on time deposits (same logic as panel) ---
for (v in c("int_exp_time_ins", "int_exp_time_unins")) {
  new_v <- paste0(v, "_q")
  dt[, (new_v) := fifelse(quarter_no == 1L, get(v), get(v) - shift(get(v), 1L)),
     by = .(ID_RSSD, cal_year)]
  dt[quarter_no > 1L & is.na(shift(get(v), 1L)), (new_v) := NA, by = .(ID_RSSD, cal_year)]
}

# --- average balances (t and t-1) ---
# RIADHK03 covers ALL time deposits <= $250k; the matching balance is
# RCONJ473 ($100k-$250k) + RCON6648 (< $100k). RIADHK04 matches RCONJ474.
dt[, ins_td_all := ins_time_deps + time_deps_lt100k]
dt[, `:=`(
  ins_td_avg   = (ins_td_all + shift(ins_td_all, 1L)) / 2,
  unins_td_avg = (unins_time_deps + shift(unins_time_deps, 1L)) / 2
), by = ID_RSSD]

# --- annualized implied rates (%); require avg balance >= $250k ---
dt[, rate_ins_td := fifelse(
  !is.na(ins_td_avg) & ins_td_avg >= 250 & !is.na(int_exp_time_ins_q) &
    int_exp_time_ins_q >= 0,
  400 * int_exp_time_ins_q / ins_td_avg, NA_real_)]
dt[, rate_unins_td := fifelse(
  !is.na(unins_td_avg) & unins_td_avg >= 250 & !is.na(int_exp_time_unins_q) &
    int_exp_time_unins_q >= 0,
  400 * int_exp_time_unins_q / unins_td_avg, NA_real_)]

winsorize_by_date(dt, c("rate_ins_td", "rate_unins_td"))
dt[, rate_spread_td := rate_unins_td - rate_ins_td]

out <- dt[!is.na(rate_ins_td) | !is.na(rate_unins_td),
          .(ID_RSSD, D_DT, rate_ins_td, rate_unins_td, rate_spread_td)]

out_path <- file.path(TRACK_DATA, paste0("td_rates_", dat_suffix, ".rds"))
saveRDS(out, out_path)

# --- diagnostics (verify-before-moving-on block) ---
cat("\n================ td_rates DIAGNOSTICS ================\n")
cat("Rows:", nrow(out), "| unique banks:", uniqueN(out$ID_RSSD), "\n")
cat("Span:", format(min(out$D_DT)), "to", format(max(out$D_DT)), "\n")
cat("NA counts: rate_ins_td", sum(is.na(out$rate_ins_td)),
    "| rate_unins_td", sum(is.na(out$rate_unins_td)),
    "| spread", sum(is.na(out$rate_spread_td)), "\n")
qs <- function(x) round(quantile(x, c(.01, .5, .99), na.rm = TRUE), 3)
cat("rate_ins_td   p1/p50/p99:", qs(out$rate_ins_td), "\n")
cat("rate_unins_td p1/p50/p99:", qs(out$rate_unins_td), "\n")
cat("spread        p1/p50/p99:", qs(out$rate_spread_td), "\n")
cat("Mean spread by year:\n")
print(out[, .(mean_spread = round(mean(rate_spread_td, na.rm = TRUE), 3)),
          keyby = .(year = year(D_DT))])
cat("Wrote:", out_path, "\n")
